name: MobSpawnerRange
main: com.flyaway.mobspawnerrange.MobSpawnerRange
version: 1.0.0
api-version: 1.21
author: FlyAwayMaking
website: https://github.com/flyawaymaking
description: Увеличивает дистанцию активации спавнеров мобов
load: POSTWORLD
folia-supported: true
library-load-order: AUTO

commands:
  spawnerrange:
    description: Основная команда плагина MobSpawnerRange
    usage: /<command> <reload|info|setrange|updateall>
    aliases: [msr, spawnerrange, mobspawner]
    permission: mobspawnerrange.info

permissions:
  mobspawnerrange.*:
    description: Все права для MobSpawnerRange
    children:
      mobspawnerrange.info: true
      mobspawnerrange.reload: true
      mobspawnerrange.setrange: true
      mobspawnerrange.admin: true
  mobspawnerrange.info:
    description: Просмотр информации о плагине
    default: op
  mobspawnerrange.reload:
    description: Перезагрузка конфигурации плагина
    default: op
  mobspawnerrange.setrange:
    description: Изменение дистанции активации спавнеров
    default: op
  mobspawnerrange.admin:
    description: Все административные права плагина
    default: op
